const IMAGE_MAP = {
  'salchipapas': 'menu_recortes/43_salchipapas.png',
  'papas fritas x kilos': 'menu_recortes/44_papas_fritas_x_kilos.png',
  'racion de chistoras': 'menu_recortes/45_racion_de_chistoras.png',
  'pastelito de carne': 'menu_recortes/46_pastelito_de_carne.png',
  'pastelito de pollo': 'menu_recortes/51_pastelito_de_pollo.png',
  'mini empanadas surtidas': 'menu_recortes/Mini_empanadas_surtidas.png',
  'combo mini empanadas': 'menu_recortes/50_combo_mini_empanadas.png',
  'tequenos de capresa x5': 'menu_recortes/48_tequenos_de_capresa_x5.png',
  'tequenos de chistorra x5': 'menu_recortes/53_tequenos_de_chistorra_x5.png',
  'tequenos de queso x5': 'menu_recortes/54_tequenos_de_queso_x5.png',
  'tequenos de papas x5': 'menu_recortes/Tequeños_de_papa.png',
  'racion de nuggets con papas': 'menu_recortes/49_racion_de_nuggets_con_papas.png',
  'hamburguesa carne': 'menu_recortes/13_hamburguesa_carne.png',
  'hamburguesa doble carne': 'menu_recortes/14_hamburguesa_doble_carne.png',
  'granjero pollo': 'menu_recortes/11_granjero_pollo.png',
  'choripan juan canalla': 'menu_recortes/10_choripan_juan_canalla.png',
  'combo choripan canalla': 'menu_recortes/12_combo_choripan_canalla.png',
  'menu ejecutivo': 'menu_recortes/Menu_ejecutivo.png',
  'perros normales': 'menu_recortes/24_perros_normales.png',
  'combo 3 perros calientes': 'menu_recortes/23_combo_3_perros_calientes.png',
  '1/8 pepperoni': 'menu_recortes/15_1-8_peperoni.png',
  '1/4 pepperoni': 'menu_recortes/18_1-4_peperoni.png',
  '1/8 campagnola': 'menu_recortes/CAMPANOLA.jpg',
  '1/4 campagnola': 'menu_recortes/CAMPANOLA.jpg',
  'capresa (entera)': 'menu_recortes/Capresa.png',
  '1/8 margarita': 'menu_recortes/21_1-8_margarita.png',
  '1/4 margarita': 'menu_recortes/20_1-4_margarita.png',
  '1 pincho de lomito': 'menu_recortes/06_1_pincho_de_lomito.png',
  'pinchos': 'menu_recortes/07_pinchos.png',
  'parrilla': 'menu_recortes/08_parrillas.png',
  'parrilla de carne': 'menu_recortes/09_parrilla_de_carne.png',
  'cuba libre': 'menu_recortes/07_cuba_libre.png',
  'destornillador': 'menu_recortes/08_destornillador.png',
  'margarita': 'menu_recortes/10_margarita.png',
  'margarita spicy': 'menu_recortes/39_margarita_spicy.png',
  'gin tonic': 'menu_recortes/11_gin_tonic.png',
  'mojito': 'menu_recortes/12_mojito.png',
  'daiquiri de fresa': 'menu_recortes/09_daiquiri_de_fresa.png',
  'daiquiri de durazno': 'menu_recortes/Daiquiri_de_durazno.png',
  'shot de limon': 'menu_recortes/Shot_de_limon.png',
  'shot de tequila': 'menu_recortes/15_shot_de_tequila.png',
  'michelada': 'menu_recortes/28_michelada.png',
  'aperol spritz': 'menu_recortes/aperol_spritz.png',
  'smirnoff trago': 'menu_recortes/40_smirnoff_trago.png',
  'stolichnaya trago': 'menu_recortes/36_stolichnaya_trago.png',
  'vodka tonic': 'menu_recortes/35_vodka_tonic.png',
  'casique': 'menu_recortes/38_casique.png',
  'casique 500': 'menu_recortes/27_casique_500.png',
  'santa teresa gran reserva': 'menu_recortes/60_santa_teresa_gran_reserva.png',
  'santa teresa linaje': 'menu_recortes/34_santa_teresa_linaje_trago.png',
  'trago silver old parr': 'menu_recortes/31_trago_silver_old_parr.png',
  'old parr trago': 'menu_recortes/41_old_parr_trago.png',
  'trago tanqueray ten': 'menu_recortes/32_trago_tanqueray_ten.png',
  "buchanan's trago": 'menu_recortes/37_buchannas_trago.png',
  'negroni': 'menu_recortes/29_negroni.png',
  'moscow mule': 'menu_recortes/30_moscow_mule.png',
  'smirnoff': 'menu_recortes/56_smirnoff.png',
  'absolut': 'menu_recortes/55_vodka_absolut.png',
  'stolichnaya': 'menu_recortes/01_vodka_stolichnaya.png',
  'ron carupano cristalino': 'menu_recortes/67_ron_carupano_cristalino.png',
  'ron cacique / cacique 500': 'menu_recortes/71_ron_cacique.png',
  'ron carupano 6 años': 'menu_recortes/57_ron_carupano_6_anos.png',
  'ron carupano 12 años': 'menu_recortes/63_ron_carupano_12_anos.png',
  'ron carupano reserva lim.': 'menu_recortes/66_ron_carupano_reserva_limitada.png',
  'black & white 0.75l': 'menu_recortes/62_black_and_white_075lts.png',
  'black & white 1l': 'menu_recortes/72_black_and_white_1litro.png',
  'old parr silver': 'menu_recortes/58_old_parr_silver.png',
  'old parr': 'menu_recortes/68_old_parr.png',
  "buchanan's": 'menu_recortes/65_buchanans.png',
  "buchanan's 18 años": 'menu_recortes/04_buchanans_18_anos.png',
  'promo whisky 12 años': 'menu_recortes/16_promocion_whisky_12_anos.png',
  'tanqueray 10': 'menu_recortes/03_tanqueray_10.png',
  'don julio reposado': 'menu_recortes/69_don_julio_reposado.png',
  'arraigo silver': 'menu_recortes/59_tequila_arraigo_silver.png',
  'volcanes de chile cab. sauv.': 'menu_recortes/05_volcanes_de_chile_cabernet_sauvignon.png',
  'castellblanc cava': 'menu_recortes/64_vino_castellblanc_cava.png',
  'aperol': 'menu_recortes/aperol.png',
  'polar pilsen': 'menu_recortes/20_polar_pilsen.png',
  'polar light': 'menu_recortes/21_polar_light.png',
  'solera azul': 'menu_recortes/22_solera_azul.png',
  'solera verde': 'menu_recortes/23_solera_verde.png',
  'tobo polar light': 'menu_recortes/02_tobo_polar_light.png',
  'tobo polar pilsen': 'menu_recortes/04_tobo_polar_pilsen.png',
  'tobo zulia': 'menu_recortes/01_tobo_mixto_polar_light_y_pilsen.png',
  'tobo mixto polar light + pilsen': 'menu_recortes/01_tobo_mixto_polar_light_y_pilsen.png',
  'pepsi / golden lata 355ml': 'menu_recortes/11_pepsi_golden_lata_355ml.png',
  'refresco litrón pepsi/7up/frescolita': 'menu_recortes/13_refresco_de_litron_pepsi_7up_frescolita.png',
  'refresco de litro': 'menu_recortes/16_refresco_de_litro.png',
  'maltin polar lata 355ml': 'menu_recortes/Maltin_polar_lata_355ml.png',
  'maltin polar': 'menu_recortes/Maltin_polar.png',
  'gatorade (varios sabores)': 'menu_recortes/12_gatorade_mandarina.png',
  'té lipton 500ml': 'menu_recortes/18_te_lipton_durazno_o_limon_500ml.png',
  'agua bienestar 600ml': 'menu_recortes/Agua_bienestar_600ml.png',
  'agua minalba 600ml': 'menu_recortes/10_agua_minalba_600ml.png',
  'minalba sparkling 500ml': 'menu_recortes/05_minalba_sparkling_pet_500ml.png',
  'minalba sparkling 1l': 'menu_recortes/07_minalba_sparkling_pet_1l.png',
  'minalba sparkling lata 355ml': 'menu_recortes/08_minalba_sparkling_soda_lata_355ml.png',
  'aguakina (agua tónica)': 'menu_recortes/Aguakina_Agua_tonica.png',
  'aguakina': 'menu_recortes/Aguakina_Agua_tonica.png',
  'jugo durazno': 'menu_recortes/20_jugo_durazno.png',
  'jugo de mora': 'menu_recortes/22_jugo_de_mora.png',
  'jugo de fresa / vaso': 'menu_recortes/25_jugo_de_fresa.png',
  'vaso jugo de naranja': 'menu_recortes/24_vaso_jugo_de_naranja.png',
  'limonada frappé': 'menu_recortes/limonada_frappe.png',
  'yukery botella 250ml': 'menu_recortes/23_yukery_botella_250ml.png',
  'café expreso': 'menu_recortes/01_cafe_expreso.png',
  'café americano': 'menu_recortes/05_cafe_americano.png',
  'café negro grande': 'menu_recortes/06_cafe_negro_grande.png',
  'café marrón pequeño': 'menu_recortes/04_cafe_marron_pequeno.png',
  'toddy mediano': 'menu_recortes/03_toddy_frio_o_caliente_mediano.png',
  'toddy grande': 'menu_recortes/02_toddy_frio_o_caliente_grande.png'
};

function normalizeName(name) {
  return (name || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, ' ').trim();
}

function normalizeKey(name) {
  return normalizeName(name).replace(/ /g, '');
}

const NORMALIZED_IMAGE_MAP = Object.fromEntries(
  Object.entries(IMAGE_MAP).map(([key, value]) => [normalizeKey(key), value])
);

function getImageForItem(name) {
  const key = normalizeKey(name);
  return NORMALIZED_IMAGE_MAP[key] || IMAGE_MAP[normalizeName(name)] || null;
}

const DATA = {
  1: [
    {n:'Salchipapas', p:'$6.80'},
    {n:'Papas Fritas x Kilos', p:'$5.80'},
    {n:'Ración de Chistoras', p:'$6.00'},
    {n:'Pastelito de Carne', p:'$1.50'},
    {n:'Pastelito de Pollo', p:'$1.50'},
    {n:'Mini Empanadas Surtidas', p:'$1.00'},
    {n:'Combo Mini Empanadas', p:'$5.00'},
    {n:'Tequeños de Capresa x5', p:'$7.00'},
    {n:'Tequeños de Chistorra x5', p:'$8.50'},
    {n:'Tequeños de Queso x5', p:'$6.96'},
    {n:'Tequeños de Papas x5', p:null},
    {n:'Ración de Nuggets con Papas', p:'$8.70'},
  ],
  2: [
    {n:'Hamburguesa Carne', p:'$9.00'},
    {n:'Hamburguesa Doble Carne', p:'$11.60'},
    {n:'Granjero Pollo', p:'$8.50'},
    {n:'Choripán Juan Canalla', p:'$5.00'},
    {n:'Combo Choripán Canalla', p:'$12.00'},
    {n:'Menú Ejecutivo', p:'$8.00'},
    {n:'Perros Normales', p:'$1.50'},
    {n:'Combo 3 Perros Calientes', p:'$4.00'},
  ],
  3: [
    {n:'1/8 Pepperoni', p:'$5.80'},
    {n:'1/4 Pepperoni', p:'$11.02'},
    {n:'1/8 Campagnola', p:'$6.38'},
    {n:'1/4 Campagnola', p:'$12.76'},
    {n:'Capresa (entera)', p:'$15.08'},
    {n:'1/8 Margarita', p:'$5.80'},
    {n:'1/4 Margarita', p:'$9.86'},
  ],
  4: [
    {n:'1 Pincho de Lomito', p:'$5.00'},
    {n:'Pinchos', p:null},
    {n:'Parrilla', p:null},
    {n:'Parrilla de Carne', p:'$16.24'},
  ],
  5: [
    {n:'Cuba Libre', p:'$7.00'},
    {n:'Destornillador', p:'$7.00'},
    {n:'Margarita', p:'$8.00'},
    {n:'Margarita Spicy', p:'$10.00'},
    {n:'Gin Tonic', p:'$8.00'},
    {n:'Mojito', p:'$9.00'},
    {n:'Daiquiri de Fresa', p:'$11.00'},
    {n:'Daiquiri de Durazno', p:null},
    {n:'Shot de Limón', p:'$2.00'},
    {n:'Shot de Tequila', p:'$7.50'},
  ],
  6: [
    {n:'Michelada', p:'$1.80'},
    {n:'Aperol Spritz', p:'$6.50'},
    {n:'Smirnoff Trago', p:'$6.50'},
    {n:'Stolichnaya Trago', p:'$4.64'},
    {n:'Vodka Tonic', p:'$8.00'},
    {n:'Casique', p:'$7.00'},
    {n:'Casique 500', p:'$8.00'},
    {n:'Santa Teresa Gran Reserva', p:'$7.00'},
    {n:'Santa Teresa Linaje', p:'$8.00'},
    {n:'Trago Silver Old Parr', p:'$7.00'},
    {n:'Old Parr Trago', p:'$9.00'},
    {n:'Trago Tanqueray Ten', p:'$9.50'},
    {n:"Buchanan's Trago", p:'$9.00'},
    {n:'Negroni', p:'$13.00'},
    {n:'Moscow Mule', p:'$11.00'},
  ],
  7: [
    {n:'Smirnoff', p:'$46.40'},
    {n:'Absolut', p:'$52.20'},
    {n:'Stolichnaya', p:'$45.00'},
    {n:'Ron Carupano Cristalino', p:'$25.00'},
    {n:'Ron Cacique / Cacique 500', p:'$28.00'},
    {n:'Ron Carupano 6 Años', p:'$20.00'},
    {n:'Ron Carupano 12 Años', p:'$35.00'},
    {n:'Santa Teresa Gran Reserva', p:'$46.40'},
    {n:'Santa Teresa Linaje', p:'$58.00'},
    {n:'Ron Carupano Reserva Lim.', p:'$45.00'},
    {n:'Black & White 0.75L', p:'$30.00'},
    {n:'Black & White 1L', p:'$35.00'},
    {n:'Old Parr Silver', p:'$52.20'},
    {n:'Old Parr', p:'$55.00'},
    {n:"Buchanan's", p:'$60.00'},
    {n:"Buchanan's 18 Años", p:'$162.40'},
    {n:'Promo Whisky 12 Años', p:'$56.84'},
    {n:'Tanqueray 10', p:'$92.80'},
    {n:'Don Julio Reposado', p:'$95.00'},
    {n:'Arraigo Silver', p:'$55.00'},
    {n:'Volcanes de Chile Cab. Sauv.', p:'$29.00'},
    {n:'CastellBlanc Cava', p:'$29.00'},
    {n:'Aperol', p:null},
  ],
  8: [
    {n:'Polar Pilsen', p:'$1.74'},
    {n:'Polar Light', p:'$1.74'},
    {n:'Solera Azul', p:'$1.98'},
    {n:'Solera Verde', p:'$1.97'},
    {n:'Tobo Polar Light', p:'$10.00'},
    {n:'Tobo Polar Pilsen', p:'$10.00'},
    {n:'Tobo Mixto Polar Light + Pilsen', p:'$10.00'},
  ],
  9: [
    {n:'Pepsi / Golden Lata 355ml', p:'$2.00'},
    {n:'Refresco Litrón Pepsi/7up/Frescolita', p:'$3.80'},
    {n:'Refresco de Litro', p:'$3.50'},
    {n:'Maltin Polar Lata 355ml', p:'$2.00'},
    {n:'Maltin Polar', p:'$1.16'},
    {n:'Gatorade (varios sabores)', p:'$3.00'},
    {n:'Té Lipton 500ml', p:'$3.00'},
    {n:'Agua Bienestar 600ml', p:'$1.80'},
    {n:'Agua Minalba 600ml', p:'$2.00'},
    {n:'Minalba Sparkling 500ml', p:'$3.00'},
    {n:'Minalba Sparkling 1L', p:'$4.00'},
    {n:'Minalba Sparkling Lata 355ml', p:'$2.50'},
    {n:'Aguakina (Agua Tónica)', p:'$3.00'},
  ],
  10: [
    {n:'Jugo Durazno', p:'$3.80'},
    {n:'Jugo de Mora', p:'$3.80'},
    {n:'Jugo de Fresa / vaso', p:'$3.80–$4.64'},
    {n:'Vaso Jugo de Naranja', p:'$2.32'},
    {n:'Limonada Frappé', p:'$3.50'},
    {n:'Yukery Botella 250ml', p:'$2.00'},
    {n:'Café Expreso', p:'$1.50'},
    {n:'Café Americano', p:'$2.00'},
    {n:'Café Negro Grande', p:'$2.50'},
    {n:'Café Marrón Pequeño', p:'$3.00'},
    {n:'Toddy Mediano', p:'$3.00'},
    {n:'Toddy Grande', p:'$4.50'},
  ]
};
